name: Unit Tests
on: [push]
jobs:
  Python-3-Tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [3.8, 3.11]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements3.txt
          pip install codecov

      - name: Run test cases
        run: pytest --cov=mitxgraders --cov-report=term-missing

      - name: Run coverage
        run: codecov
